### ISSUE TITLE
why am i getting this error

### ISSUE THREAD

**Issue by Fallden4** [faveris/glyph_extractor#2]
```
Traceback (most recent call last):
  File "C:\Users\htauk\Downloads\glyph_extractor-main\glyph_extractor-main\extract_glyphs.py", line 3, in <module>
    import cairosvg.surface
  File "C:\Python312\Lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Python312\Lib\site-packages\cairocffi\__init__.py", line 47, in <module>
    cairo = dlopen(
            ^^^^^^^
  File "C:\Python312\Lib\site-packages\cairocffi\__init__.py", line 44, in dlopen
    raise OSError(error_message)  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.so.2'
cannot load library 'libcairo.2.dylib': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.2.dylib'
cannot load library 'libcairo-2.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo-2.dll'
```

i dont know what the hell i did wrong

**Comment by faveris** [comment]
The glyph extractor requires the Cairo library for extracting glyphs with embedded colors. Please refer to the Cairo documentation for [installation instructions](https://cairosvg.org/documentation/#installation).

Or you can attempt to use the `--no-embed-colors` parameter, but please note that glyphs won't be colored in this case.
