### ISSUE TITLE
Invalid pixel size error

### ISSUE THREAD

**Issue by Abdulmalekak** [faveris/glyph_extractor#3]
hi so I tired to extract the note emoji file of my phone and kept getting this error
Traceback (most recent call last):
  File "C:\Users\Abdulmalek\glyph_extractor\extract_glyphs.py", line 199, in <module>
    imagefont = ImageFont.truetype(fontPath, size)
  File "C:\Users\Abdulmalek\AppData\Roaming\Python\Python310\site-packages\PIL\ImageFont.py", line 819, in truetype
    return freetype(font)
  File "C:\Users\Abdulmalek\AppData\Roaming\Python\Python310\site-packages\PIL\ImageFont.py", line 816, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Users\Abdulmalek\AppData\Roaming\Python\Python310\site-packages\PIL\ImageFont.py", line 245, in __init__
    self.font = core.getfont(
OSError: invalid pixel size

thanks before hand for the help
also how can i reformat it into a ttf file after making a few edits

**Comment by faveris** [comment]
Hi,
Could you please share a link to the font file?

**Comment by Abdulmalekak** [comment]
here you go good luck with it
https://drive.google.com/file/d/1ip1YQKge2RWuvI2WrBTifugK026uRWrW/view?usp=drive_link

**Comment by faveris** [comment]
Thanks.
The glyph extractor cannot determine the correct size for this font. I'll attempt to find a solution. Please try using the parameter `--size 109` as a workaround.
