### ISSUE TITLE
`no-embed-color` fails on Apple Color Emoji

### ISSUE THREAD

**Issue by mattppal** [faveris/glyph_extractor#4]
Running `python extract_glyphs.py "/System/Library/Fonts/Apple Color Emoji.ttc" --no-embed-color`, I get the following error:

```
Using font size 160
Traceback (most recent call last):
  File "/Users/matt/git-repos/glyph_extractor/extract_glyphs.py", line 208, in <module>
    (left, top, right, bottom) = imagefont.getbbox(text)
  File "/Users/matt/.pyenv/versions/glyph-extractor/lib/python3.10/site-packages/PIL/ImageFont.py", line 421, in getbbox
    size, offset = self.font.getsize(
ValueError: raqm_get_glyphs() failed.
```

Omitting the `--no-embed-color`, I get a successful run through 🫲.5.R -> 0x1faf2.5.R.png:

```
Traceback (most recent call last):
  File "/Users/matt/git-repos/glyph_extractor/extract_glyphs.py", line 208, in <module>
    (left, top, right, bottom) = imagefont.getbbox(text)
  File "/Users/matt/.pyenv/versions/glyph-extractor/lib/python3.10/site-packages/PIL/ImageFont.py", line 421, in getbbox
    size, offset = self.font.getsize(
ValueError: raqm_get_glyphs() failed.
```

I won't have time to investigate for a few days, but I'll plan to take a look soon.

**Comment by faveris** [comment]
Should be fixed in PR #5 

Thanks for reporting!
